#!/bin/bash 
echo -e "\nAbout to copy backed-up code for assignment $1\n"

function check-folder {
    if [ -d "$1" ];
    then
        echo "$1 folder already exists on your local system."
        echo "Are you sure you want to overwrite your local files? (y/n) "
        read yn
        while [[ "$yn" != "y" && "$yn" != "n" ]]; 
        do
            echo -e "Enter one of (y/n): "
            read yn
        done
        if [ "$yn" == "n" ]; then
            echo "Quitting..."
            exit 1
        fi 
    else 
        mkdir $1
    fi    
}

remotefolder=`jq .remotePath /workspaces/cs-175/.vscode/sftp.json | tr '/' '\n' | tail -1 | rev | cut -c 2- | rev`
if [ "$2" ];
then
    if [ "$2" != "-s" ]; then
        echo -e "Usage: pull-backup hwname [-s snapshot_directory]"
    else 
        check-folder "$1-backup-$3"
        scp -r "${utln}@homework.cs.tufts.edu:~/.snapshot/$3/${remotefolder}/$1/*" "./$1-backup-$3/"
    fi
else    
    check-folder "$1-backup"
    scp -r "${utln}@homework.cs.tufts.edu:~/${remotefolder}/$1/*" "./$1-backup/"
fi
